project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "Stocks"
  author:
    - JJ Zhang (jz3980)
    - Xinxin Zhang (xz2843)
  repo-url: https://github.com/junjunzhang1998/movie-stocks
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: minty
    code-fold: true


